# Maestro configuration for Brik Example App
name: Brik Example App E2E Tests
appId: com.mukulchugh.rn-expo-app

# Default settings
env:
  SCREENSHOT_DIR: "screenshots"
  TIMEOUT: 30000

# Tags for test organization
tags:
  smoke: "Quick smoke tests"
  critical: "Critical user paths"
  widget: "Widget-related tests"
  live-activity: "Live Activity tests"
  ios-only: "iOS-specific tests"
  android-only: "Android-specific tests"
  on:pr: "Run on pull requests"
  on:nightly: "Run on nightly builds"

# Platform-specific config
ios:
  permissions:
    notifications: ALLOW
    location: DENY

android:
  permissions:
    notifications: ALLOW
    location: DENY
