import * as fs from 'fs'
import * as path from 'path'

import type { WidgetFiles } from '../types'

/**
 * Scans the widget extension target directory and returns categorized file lists.
 *
 * This function only reads the directory structure - it does NOT copy or create files.
 * File generation should be done before this is called.
 *
 * @param targetPath - Path to the widget extension target directory
 * @param targetName - Name of the target (for entitlements file)
 * @returns Categorized lists of files for Xcode project configuration
 */
export function getWidgetFiles(targetPath: string, targetName: string): WidgetFiles {
  const widgetFiles: WidgetFiles = {
    swiftFiles: [],
    entitlementFiles: [],
    plistFiles: [],
    assetDirectories: [],
    intentFiles: [],
  }

  if (!fs.existsSync(targetPath)) {
    // Still include required generated files even if directory doesn't exist yet
    const initialStatesFile = 'VoltraWidgetInitialStates.swift'
    widgetFiles.swiftFiles.push(initialStatesFile)
    const targetEntitlements = `${targetName}.entitlements`
    widgetFiles.entitlementFiles.push(targetEntitlements)
    return widgetFiles
  }

  const files = fs.readdirSync(targetPath)

  for (const file of files) {
    const itemPath = path.join(targetPath, file)
    const isDirectory = fs.lstatSync(itemPath).isDirectory()

    // Handle directories (Assets.xcassets)
    if (isDirectory) {
      if (file === 'Assets.xcassets') {
        widgetFiles.assetDirectories.push(file)
      }
      continue
    }

    // Categorize files by extension
    const ext = path.extname(file).toLowerCase()

    switch (ext) {
      case '.swift':
        widgetFiles.swiftFiles.push(file)
        break
      case '.entitlements':
        widgetFiles.entitlementFiles.push(file)
        break
      case '.plist':
        widgetFiles.plistFiles.push(file)
        break
      case '.intentdefinition':
        widgetFiles.intentFiles.push(file)
        break
    }
  }

  // Always include the target entitlements file
  const targetEntitlements = `${targetName}.entitlements`
  if (!widgetFiles.entitlementFiles.includes(targetEntitlements)) {
    widgetFiles.entitlementFiles.push(targetEntitlements)
  }

  // Always include VoltraWidgetInitialStates.swift (generated by config plugin)
  const initialStatesFile = 'VoltraWidgetInitialStates.swift'
  if (!widgetFiles.swiftFiles.includes(initialStatesFile)) {
    widgetFiles.swiftFiles.push(initialStatesFile)
  }

  return widgetFiles
}
