name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          version: 2025.9.18

      - name: Install tools via mise
        run: |
          mise install
          mise trust

      - name: Verify tool versions
        run: mise current

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Build widgets
        run: mise run widgets

      - name: Create release
        run: echo "Release via Changesets can be added later"
